#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
#shellcheck source=checks.sh
#shellcheck source=config.sh
#shellcheck source=exec.sh
#shellcheck source=helpers.sh
#shellcheck source=geyser.sh
#shellcheck source=jenkins.sh
#shellcheck source=modrinth.sh
#shellcheck source=purpur.sh
#shellcheck disable=SC2164
#shellcheck disable=SC2162

set -u

### DO NOT EDIT THIS FILE

### Required Sources (cannot be outsourced because we are checking if those sources are OK)

DIRNAME="$(dirname "${0}")"
REQUIRED_SOURCES=('checks.sh' 'config.sh' 'exec.sh' 'helpers.sh')
REQUIRED_COMMANDS=('curl' 'find' 'jq' 'md5sum' 'sha256sum' 'sha512sum')

for REQUIRED_SOURCE in "${REQUIRED_SOURCES[@]}"
do
  if [[ -f "${DIRNAME}/${REQUIRED_SOURCE}" ]] && [[ -r "${DIRNAME}/${REQUIRED_SOURCE}" ]]
  then
    #shellcheck disable=SC1090 # Shellcheck directives for sources given on first few lines
    source "${DIRNAME}/${REQUIRED_SOURCE}"
  else
    printf '%s\n' "The required ${REQUIRED_SOURCE} is either absent from the same directory as ${0} or unable to be read. Aborting ..."
    exit 3
  fi
done

for REQUIRED_COMMAND in "${REQUIRED_COMMANDS[@]}"
do
  which "${REQUIRED_COMMAND}" &>/dev/null || \
    error_out 3 "The command \`${REQUIRED_COMMAND}\` is not installed on your system. Please install it to run this script. Exiting ..."
done

### Remaining pre-init

TIMESTAMP="${TARGET_DIR}/.timestamp"
timestamp_check # .timestamp
LAST_RUN="$(date '+%s' -d "$(cat "${TIMESTAMP}" 2>/dev/null)")"
export LAST_RUN REQUIRED_SOURCES TIMESTAMP
[[ "${DEBUG}" == 'true' ]] && set -xa
target_dir_check
trap 'handle_ctrl_c' SIGINT # helpers.sh

### Exec

pushd "${TARGET_DIR}"
#shellcheck disable=SC2153
for SOURCE in "${OPTIONAL_SOURCES[@]}"
do
  SOURCE_NAME="${SOURCE/%'.sh'}"
  optional_source_check "${SOURCE}" || continue
  . "${SOURCE}"
  source_check "${SOURCE}" || continue
  SOURCE_DIR="$(eval echo "\${${SOURCE_NAME^^}_DIR}")"
  [[ ! -d "${SOURCE_DIR}" ]] && \
    mkdir -p "${SOURCE_DIR}" 2>/dev/null # It may already exist
  pushd "${SOURCE_DIR}"
  "${SOURCE_NAME}_exec"
  popd
done
popd

### Open UNAVAILABLE links

msg "Plugins to update manually: ${!UNAVAILABLE[*]}"
qq 'Automatically open their URLs ?'
read -n 1 ANSWER
printf '\n'
if [[ "${ANSWER}" = 'y' ]] || [[ "${ANSWER}" = 'Y' ]]
then
  case "$(uname)" in
    'Darwin')
      OPEN='open'
      ;;
    *)
      OPEN='xdg-open'
      ;;
  esac
  for LINK in "${!UNAVAILABLE[@]}"
  do
    "${OPEN}" "${UNAVAILABLE["${LINK}"]}"
  done
fi

### Update Timestamp

update_timestamp
