#!/usr/bin/env python
import os
from helpers import *
from modrinth import *
import glob

### DO NOT EDIT THIS FILE

dirname = os.path.dirname(__file__)

out('hello')

modrinth_test = Modrinth('Chunky')
modrinth_test.eval_glob('Chunky-*.jar')
modrinth_test.download()
