#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
### DO NOT EDIT THIS FILE

bad_source(){
  error "${1} does not follow its definition (does not include the necessary variables). Skipping ..."
  return 1
}

corrupt(){
  error "${1} did not download properly. Please download manually."
}

error(){
  printf ' \033[;1;31m==>\033[;0m \033[;1mERROR: %s\033[;0m\n' "${*}"
}

error_out(){
  local EXIT_CODE="${1}"
  shift
  error "${*}"
  exit "${EXIT_CODE}"
}

handle_ctrl_c(){
  local ANSWER
  qq 'Update Timestamp ?'
  #shellcheck disable=SC2162
  read -n 1 -t 10 ANSWER
  if [[ "${ANSWER}" == 'y' ]] || [[ "${ANSWER}" == 'Y' ]]
  then
    update_timestamp
  fi
  exit 1
}

hash_fix(){
  head -c '-4' -
}

msg(){
  printf ' \033[;1;32m==>\033[;0m \033[;1m%s \033[;0m\n' "${*}"
}

msg_nonew(){
  printf ' \033[;1;32m==>\033[;0m \033[;1m%s \033[;0m' "${*}"
}

qq(){
  printf ' \033[;1;33m==>\033[;0m \033[;1m%s (y/n) :\033[;0m ' "${*}"
}

update_timestamp(){
  msg 'Updating Timestamp ...'
  msg 'Date of last run: ' "$(cat "${TIMESTAMP}")"
  date > "${TIMESTAMP}"
}

uptodate(){
  msg "${1}" 'is up to date ( Last update at' "$(date -d "${2}" '+%b %d %H:%M %Y')" ')'
}

updating(){
  msg 'Updating' "${1}..." '( Updated at' "$(date -d "${2}" '+%b %d %H:%M %Y')" ')'
}
