#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
#shellcheck disable=SC1090 # Directives handled in download.sh
#shellcheck disable=SC2034
### DO NOT EDIT THIS FILE

GEYSER_DEFINITION=(
  '@API_URL'
  '@DIR'
  'NAMES'
  'PROJECTS'
)

JENKINS_DEFINITION=(
  '@DIR'
  'NAMES'
  'PATHS'
  'URLS'
)

MODRINTH_DEFINITION=(
  '@API_URL'
  'BACKUPS'
  '@DIR'
  'NAMES'
  '@PAYLOAD'
  'WILDCARDS'
)

PURPUR_DEFINITION=(
  '@API_URL'
  '@DIR'
  'NAMES'
  'PROJECTS'
  'WILDCARDS'
)

UNAVAILABLE_DEFINITION=(
  '@COMMAND'
  'NAMES'
  'URLS'
)

bash_check(){
  [[ "${BASH_VERSINFO[0]}" -le 3 ]] && \
    error_out '5' 'Please install a newer version of bash to run this script (minimum 4.0.0).'
}

rw_check(){
  local OPTIONAL_SOURCE
  OPTIONAL_SOURCE="${TARGET_DIR}/sources/${1}"
  if [[ -f "${OPTIONAL_SOURCE}" ]] && [[ -r "${OPTIONAL_SOURCE}" ]] # Custom script in target dir
  then
    source "${OPTIONAL_SOURCE}"
  else
    error "The source ${OPTIONAL_SOURCE} is either absent or unable to be read. Skipping ..."
    return 1
  fi
}

optional_source_check(){
  set +u # We're dealing with that here
  local ARRAY_LENGTH BASE FULL_VAR NUM VARIABLE
  trap 'bad_source && return 1' SIGHUP
  BASE="$(hash_fix <<< "${1}")" # `hash_fix` cuts of last 3 chars, which is a coincidence but is useful here.
  for VARIABLE in $(eval echo "\${${BASE^^}_DEFINITION[@]}") # `printf` only prints first arg, whereas `echo` prints them all
  do
    FULL_VAR="$(tr -d '@%' <<< "${BASE^^}_${VARIABLE}")"
    case "${VARIABLE:0:1}" in
      '@')
        [[ -z "${!FULL_VAR}" ]] && \
          printf '%s' "${FULL_VAR} "
        ;;
      '%')
        [[ -z "${!VARIABLE}" ]] && \
          printf '%s' "${VARIABLE}"
        ;;
      *)
        ARRAY_LENGTH="$(eval printf "\${#${FULL_VAR}[@]}")" 2>/dev/null
        if [[ "${NUM}" ]] && [[ "${ARRAY_LENGTH}" != "${NUM}" ]]
        then
          printf '%s' "${FULL_VAR}"
        else
          NUM="${ARRAY_LENGTH}"
        fi
    esac
  done
  set -u
}

target_dir_check(){
  if ! { [[ -d "${1}" ]] && [[ -r "${1}" ]] && [[ -w "${1}" ]] ; }
  then
    mkdir -p "${1}" 2>/dev/null # Silence errors because ${1} may already exist.
    # Attempt to fix permissions automatically
    chmod -R '+rw' "${1}" || \
      error_out '6' 'The directory ' "${1}" 'either cannot be created or cannot be made readable and writable (rw). '
  fi
}

timestamp_check(){
  if [[ ! -f "${TIMESTAMP}" ]]
  then
    printf '%s' 'Thu Jan 1 00:00:00 GMT 1970' > "${TIMESTAMP}"
  fi
}
