#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
#shellcheck disable=SC1090 # Directives handled in download.sh
### DO NOT EDIT THIS FILE

GEYSER_DEFINITION=(
  '@API_URL'
  '@DIR'
  'NAMES'
  'PROJECTS'
)

JENKINS_DEFINITION=(
  '@DIR'
  'NAMES'
  'PATHS'
  'URLS'
)

MODRINTH_DEFINITION=(
  '@API_URL'
  'BACKUPS'
  '@DIR'
  'NAMES'
  '@PAYLOAD'
  'WILDCARDS'
)

PURPUR_DEFINITION=(
  '@API_URL'
  '@DIR'
  'NAMES'
  'PROJECTS'
  'WILDCARDS'
)

UNAVAILABLE_DEFINITION=(
  '@COMMAND'
  'NAMES'
  'URLS'
)

bash_check(){
  [[ "${BASH_VERSINFO[0]}" -le 3 ]] && \
    error_out '3' 'Please install a newer version of bash to run this script (minimum 4.0.0).'
}

optional_source_check(){
  local OPTIONAL_SOURCE="${1}"
  #shellcheck disable=SC2153
  CUSTOM_SOURCE="${TARGET_DIR}/${OPTIONAL_SOURCE}"
  if [[ -f "${CUSTOM_SOURCE}" ]] && [[ -r "${CUSTOM_SOURCE}" ]] # Custom script in target dir
  then
    source "${CUSTOM_SOURCE}"
  elif [[ -f "${DIRNAME}/${OPTIONAL_SOURCE}" ]] && [[ -r "${DIRNAME}/${OPTIONAL_SOURCE}" ]] # Our stock script
  then
    source "${DIRNAME}/${OPTIONAL_SOURCE}"
  else
    error "The optional  ${OPTIONAL_SOURCE} is either absent or unable to be read. Skipping ..."
  fi
}

source_check(){
  set +u # We're dealing with that here
  local ARRAY_LENGTH BASE FULL_VAR NUM VARIABLE
  BASE="$(hash_fix <<< "${1}")" # `hash_fix` cuts of last 3 chars, which is a coincidence but is useful here.
  NUM='' # Needs to be reset for every source
  for VARIABLE in $(eval echo "\${${BASE^^}_DEFINITION[@]}") # `printf` only prints first arg, whereas `echo` prints them all
  do
    FULL_VAR="${BASE^^}_${VARIABLE#@}"
    if [[ "${VARIABLE:0:1}" == '@' ]]
    then
      if [[ -z "${FULL_VAR}" ]]
      then
        bad_source "${1}"
        return 1
      fi
    else
      ARRAY_LENGTH="$(eval printf "\${#${FULL_VAR}[@]}")" 2>/dev/null
      if [[ "${NUM}" ]] && [[ "${ARRAY_LENGTH}" != "${NUM}" ]]
      then
        bad_source "${1}"
	return 1
      else
        NUM="${ARRAY_LENGTH}"
      fi
    fi
  done
  set -u
}

target_dir_check(){
  if ! { [[ -d "${TARGET_DIR}" ]] && [[ -r "${TARGET_DIR}" ]] && [[ -w "${TARGET_DIR}" ]] ; }
  then
    mkdir -p "${TARGET_DIR}" 2>/dev/null # Silence errors because TARGET_DIR may already exist.
    # Attempt to fix permissions automatically
    chmod -R '+rw' "${TARGET_DIR}" || \
      error_out '2' 'The target directory ' "${TARGET_DIR}" 'either cannot be created or cannot be made readable and writable (rw). '
  fi
}

timestamp_check(){
  if [[ ! -f "${TIMESTAMP}" ]]
  then
    printf '%s' 'Thu Jan 1 00:00:00 GMT 1970' > "${TIMESTAMP}"
  fi
}
