#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
#shellcheck disable=SC2086
### DO NOT EDIT THIS FILE
geyser_hash_check(){
  [[ ! -f "${OUTPUT}" ]] && return 1
  [[ "$(sha256sum < "./${OUTPUT}" | hash_fix)" == "$(jq -r '.downloads.spigot.sha256' <<< "${RECEIPT}")" ]]
  # 2>/dev/null because "./${OUTPUT}" may not exist
}

geyser_exec(){
  local OUTPUT RECEIPT TIMESTAMP
  local -i i
  for (( i = 0 ; i < "${#GEYSER_PROJECTS[@]}" ; i++ ))
  do
    RECEIPT="$(curl -sL "${GEYSER_API_URL}/projects/${GEYSER_PROJECTS["${i}"]}/versions/latest/builds/latest")"
    TIMESTAMP="$(jq -r '.time' <<< "${RECEIPT}")"
    OUTPUT="$(jq -r '.downloads.spigot.name' <<< "${RECEIPT}")"
    if geyser_hash_check && [[ "${UPDATE_MODE}" == 'true' ]]
    then
      uptodate "${GEYSER_NAMES["${i}"]}" "${TIMESTAMP}"
      continue
    fi
    updating "${GEYSER_NAMES["${i}"]}" "${TIMESTAMP}"
    curl -L# "${GEYSER_API_URL}/projects/${GEYSER_PROJECTS["${i}"]}/versions/latest/builds/latest/downloads/spigot" -o "./${OUTPUT}"
    geyser_hash_check || corrupt "${GEYSER_NAMES["${i}"]}"
  done
}

jenkins_exec(){
  local RECEIPT TIMESTAMP
  local -i i
  for (( i = 0 ; i < "${#JENKINS_NAMES[@]}" ; i++ ))
  do
    RECEIPT="$(curl -s "https://${JENKINS_URLS["${i}"]}/lastSuccessfulBuild/api/json")"
    TIMESTAMP="$(jq -r '.timestamp' <<< "${RECEIPT}" | head -c '-4')"
    if [[ "${TIMESTAMP}" -lt "${LAST_RUN}" ]]
    then
      uptodate "${JENKINS_NAMES["${i}"]}" "@${TIMESTAMP}"
      continue
    fi
    updating "${JENKINS_NAMES["${i}"]}" "@${TIMESTAMP}"
    #shellcheck disable=SC2086 # Word splitting intended for CURL_ARGS
    curl ${CURL_ARGS} "https://${JENKINS_URLS["${i}"]}/lastSuccessfulBuild/artifact/$(\
      jq -r '.artifacts[].relativePath' <<< "${RECEIPT}" | \
      grep "${JENKINS_PATHS["${i}"]}")"
  done
}

modrinth_download(){
  updating "${MODRINTH_NAMES["${i}"]}" "$(jq -r '.date_published' <<< "${RECEIPT}")"
  curl ${CURL_ARGS} "$(jq -r '.files[].url' <<< "${RECEIPT}")"
}

modrinth_exec(){
  local HASH FILE RECEIPT
  local -i i
  for ((i = 0 ; i < "${#MODRINTH_NAMES[@]}" ; i++))
  do
    FILE="$(find . -maxdepth 1 -name ${MODRINTH_WILDCARDS["${i}"]})"
    if [[ -f "${FILE}"  ]]
    then
      HASH="$(sha512sum < "${FILE}" | hash_fix)"
      RECEIPT="$(curl -sX 'POST' "${MODRINTH_API_URL}/version_file/${HASH}/update?algorithm=sha512"  -H 'Content-Type: application/json' --data-binary "${MODRINTH_PAYLOAD}")"
      if [[ "$(date '+%s' -d "$(jq -r '.date_published' <<< "${RECEIPT}")")" -lt \
        "${LAST_RUN}" ]] && [[ "${UPDATE_MODE}" == 'true' ]]
      then
        uptodate "${MODRINTH_NAMES["${i}"]}" "$(jq -r '.date_published' <<< "${RECEIPT}")"
        continue
      fi
      rm "${FILE}"
    else
      RECEIPT="$(curl -sX 'POST' "${MODRINTH_API_URL}/version_file/${MODRINTH_BACKUPS["${i}"]}/update?algorithm=sha512"  -H 'Content-Type: application/json' --data-binary "${MODRINTH_PAYLOAD}")"
    fi
    modrinth_download
  done
}

purpur_exec(){
  local FILE RECEIPT REMOTE_MD5 TIMESTAMP
  local -i i
  for ((i = 0 ; i < "${#PURPUR_NAMES[@]}" ; i++))
  do
    FILE="$(find . -name ${PURPUR_WILDCARDS["${i}"]})"
    RECEIPT="$(curl -s "${PURPUR_API_URL}${PURPUR_PROJECTS["${i}"]}/${MINECRAFT_MINOR}/latest")"
    REMOTE_MD5="$(jq -r '.md5' <<< "${RECEIPT}")"
    TIMESTAMP="$(jq -r '.timestamp' <<< "${RECEIPT}" | head -c '-3')"
    if [[ "$(md5sum < "${FILE:-/dev/null}" | hash_fix)" == "${REMOTE_MD5}" ]] && [[ "${UPDATE_MODE}" == 'true' ]]
    then
      uptodate "${PURPUR_NAMES["${i}"]}" "@${TIMESTAMP}"
      continue
    fi
    updating "${PURPUR_NAMES["${i}"]}" "@${TIMESTAMP}"
    [[ -f "${FILE}" ]] && \
      rm "${FILE}" # Delete old file
    msg 'Changes: ' "$(printf '\033[;0m\n')" "$(jq -r '.commits[].description' <<< "${RECEIPT}")"
    curl ${CURL_ARGS} "https://api.purpurmc.org/v2/${PURPUR_PROJECTS["${i}"]}/${MINECRAFT_MINOR}/latest/download"
    [[ "$(md5sum < "$(find . -name ${PURPUR_WILDCARDS["${i}"]})" | head -c '-4')" == "${REMOTE_MD5}" ]]  || \
      corrupt "${PURPUR_NAMES["${i}"]}"
      # Don't use FILE because we need `find` to locate the new file
  done
}

unavailable_exec(){
  # let UNAVAILABLE_DIR go unread
  local ANSWER
  msg "Project(s) to update manually: ${UNAVAILABLE_NAMES[*]}"
  qq 'Automatically open their URLs ?'
  read -n 1 -t "${WAIT}" ANSWER
  printf '\n'
  if [[ "${ANSWER,,}" = 'y' ]] || [[ -z "${ANSWER}" ]] # Accounts for people hitting enter and 10 seconds timing out
  then
    for LINK in "${UNAVAILABLE_URLS[@]}"
    do
      "${UNAVAILABLE_COMMAND}" "${UNAVAILABLE["${LINK}"]}"
    done
  fi
}
