#!/usr/bin/env bash
#shellcheck enable=require-variable-braces
#shellcheck disable=SC2164
### DO NOT EDIT THIS FILE

_popd(){
  if [[ "${PRINT_PATH}" == 'true' ]]
  then
    popd
  else
    cd - 1>/dev/null
  fi
}

_pushd(){
  if [[ "${PRINT_PATH}" == 'true' ]]
  then
    pushd "${@}"
  else
    cd "${@}"
  fi
}

alternative_choose(){
  case "${SHOW_CHANGELOG}" in
    'false')
      CHANGELOG='true'
      ;;
    *)
      CHANGELOG='changelog'
      ;;
  esac
  export CHANGELOG
}

bad_source(){
  error "${1} does not follow its definition (does not include the necessary variable(s) ${2}). Skipping ..."
}

changelog(){
  msg 'Changes:'
  printf '%s\n' "${*}"
}

corrupt(){
  error "${1} did not download properly. Please download manually."
}

error(){
  printf ' \033[;1;31m==>\033[;0m \033[;1mERROR: %s\033[;0m\n' "${*}"
}

error_out(){
  local EXIT_CODE="${1}"
  shift
  error "${*}"
  exit "${EXIT_CODE}"
}

handle_ctrl_c(){
  local ANSWER
  qq 'Update Timestamp ?'
  #shellcheck disable=SC2162
  read -n 1 -t "${WAIT}" ANSWER
  if [[ "${ANSWER}" == 'y' ]] || [[ "${ANSWER}" == 'Y' ]]
  then
    update_timestamp
  fi
  exit 1
}

hash_fix(){
  head -c '-4' -
}

help_options(){
  printf '%s\n' '
Usage: download.sh [options] <server(s)>
The server(s) must be defined in config.sh.

Options:
  -h : Display this help message
  -v : Be verbose (debug)

Error Codes:
  0 : Success
  1 : General Failure
  2 : Unrecognized command line option
  3 : A required source is missing from lib/ (reclone from Github to fix)
  4 : A command this script utilized is not installed on your system
  5 : Incompatible shell (must be Bash > 3)
  6 : The target directory cannot be created or written to (fix permissions)
'
}

msg(){
  printf ' \033[;1;32m==>\033[;0m \033[;1m%s \033[;0m\n' "${*}"
}

msg_nonew(){
  printf ' \033[;1;32m==>\033[;0m \033[;1m%s \033[;0m' "${*}"
}

qq(){
  printf ' \033[;1;33m==>\033[;0m \033[;1m%s (y/n) :\033[;0m ' "${*}"
}

update_timestamp(){
  msg 'Updating Timestamp ...'
  msg 'Date of last run: ' "$(cat "${TIMESTAMP}")"
  date > "${TIMESTAMP}"
}

uptodate(){
  msg "${1}" 'is up to date ( Last update at' "$(date -d "${2}" '+%b %d %H:%M %Y')" ')'
}

updating(){
  msg 'Updating' "${1}..." '( Updated at' "$(date -d "${2}" '+%b %d %H:%M %Y')" ')'
}
