#!/usr/bin/env
from helpers import out
from modrinth import Modrinth
from jsonfile import jsonfile

# DO NOT EDIT THIS FILE

# Modrinth Loop
mrobj = Modrinth('ViaVersion')
mrobj.populate(jsonfile('stock/modrinth.json').value)
out(mrobj)
mrobj.import_json()
mrobj.eval_glob()
out('success')
