#!/usr/bin/env python
import argparse
from helpers import out
from modrinth import Modrinth

# DO NOT EDIT THIS FILE

out("Arthurmeade12's download.py")

parser = argparse.ArgumentParser(description="Arthurmeade12's download.py")
parser.add_argument(
    '-c', '--create',
    metavar='SERVER',
    help='The name of the server to create'
)
parser.add_argument(
    "-d", "--debug", "--verbose",
    help="Print debug messages (be verbose)",
    action="store_true"
)
parser.add_argument('server', help='foo bar description')
parser.add_argument(
    '-v', '--version',
    action='version',
    version='%(prog)s 0.1 ALPHA',
    help='Print version of %(prog)s'
)
args = parser.parse_args()

out("Args : " + str(args))
# Modrinth Loop
mrobj = Modrinth(0)
out(mrobj)
mrobj._exec()
